services:
  db:
    image: postgres:15.4
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: 'Asia/Tokyo'
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile.local
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
    depends_on:
      - db
    tty: true
    stdin_open: true
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    command: 'yarn dev'
    ports:
      - '8000:3000'
    volumes:
      - ./front:/usr/src/app
volumes:
  postgres-data:
    driver: local